CREATE TABLE Drivers (
DriverID INT PRIMARY KEY,
DriverName NVARCHAR(50) NOT NULL
)

CREATE TABLE Cars (
CarID INT PRIMARY KEY IDENTITY,
DriverID INT UNIQUE NOT NULL,
CONSTRAINT FK_Cars_Drivers
FOREIGN KEY (DriverID)
REFERENCES Drivers (DriverID)
)